name: Deploy Cloud Functions

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCLOUD_SA_KEY }}'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
        service_account_key: ${{ secrets.GCLOUD_SA_KEY }}

    - name: Check if service1 has changes
      id: service1_changes
      run: |
        if git diff --quiet HEAD^ HEAD -- ./service1; then
          echo "no_changes=true" >> $GITHUB_ENV
        else
          echo "no_changes=false" >> $GITHUB_ENV
        fi

    - name: Deploy Service 1 Function
      if: env.no_changes == 'false'
      run: |
        gcloud functions deploy service1_function \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source ./service1

    - name: Check if service2 has changes
      id: service2_changes
      run: |
        if git diff --quiet HEAD^ HEAD -- ./service2; then
          echo "no_changes=true" >> $GITHUB_ENV
        else
          echo "no_changes=false" >> $GITHUB_ENV
        fi

    - name: Deploy Service 2 Function
      if: env.no_changes == 'false'
      run: |
        gcloud functions deploy service2_function \
          --runtime python39 \
          --trigger-http \
          --allow-unauthenticated \
          --source ./service2
