name: Python CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [service1, service2]  # Define your services

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          cd ${{ matrix.service }}
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest tests/${{ matrix.service }}_tests/

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Deploy only from the main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          export_default_credentials: true

      - name: Install dependencies
        run: |
          cd service1
          pip install -r requirements.txt

      - name: Deploy to Google Cloud App Engine
        run: |
          gcloud app deploy app.yaml --quiet

      - name: Deploy to Google Cloud Functions (optional)
        run: |
          gcloud functions deploy my-function --runtime python39 --trigger-http --allow-unauthenticated
